// contractClient.ts
//
// Submits a real on-chain enterRoom transaction via the Midnight Preprod network.
// Uses the real compiled circuit bindings from managed/enclave/contract/index.js
// (generated by GitHub Actions via `compact compile`).

import deployedContract from "../../deployed_contract.json";
import { WalletApi } from "./midnightWallet";

export interface DeploymentInfo {
  network: string;
  address: string | null;
}

export function getDeployment(): DeploymentInfo {
  return { network: deployedContract.network, address: deployedContract.address };
}

export function isDeployed(): boolean {
  return Boolean(deployedContract.address);
}

export interface EnterRoomParams {
  wallet: WalletApi;
  memberSecret: string;
  roomIndex: number;
}

export interface TxResult {
  txHash: string;
  explorerUrl: string;
}

export async function submitEnterRoom(params: EnterRoomParams): Promise<TxResult> {
  if (!isDeployed()) {
    throw new Error(
      "No contract is deployed yet. Fill in deployed_contract.json with a valid Preprod contract address."
    );
  }

  try {
    // Import the real compiled bindings (generated by compact compile via GitHub Actions)
    const EnclaveBindings = await import("../../managed/enclave/contract/index.js");
    console.debug("[contractClient] Loaded circuit bindings:", {
      exports: Object.keys(EnclaveBindings),
      ContractClass: EnclaveBindings.Contract,
    });

    // Import the Midnight SDK
    const { findDeployedContract } = await import("@midnight-ntwrk/midnight-js-contracts");
    console.debug("[contractClient] Midnight SDK loaded. Contract address:", deployedContract.address);

    // Build the compiled contract object. The compact compiler generates a Contract class
    // that must be instantiated with witnesses. Since this is an allowlist-proof contract,
    // the witnesses (memberSecret, memberPath) are derived from the memberSecret input.
    const memberSecretBytes = new TextEncoder().encode(params.memberSecret.padEnd(32, "\0")).slice(0, 32);

    type PrivateState = {
      memberSecret: Uint8Array;
      memberPath: { leaf: Uint8Array; path: { sibling: { field: bigint }; goes_left: boolean }[] };
    };

    // Instantiate the contract with the required witnesses
    const contractInstance = new EnclaveBindings.Contract({
      memberSecret: ({ privateState }: { privateState: PrivateState }) =>
        [privateState, privateState.memberSecret] as [PrivateState, Uint8Array],
      memberPath: ({ privateState }: { privateState: PrivateState }) =>
        [privateState, privateState.memberPath] as [PrivateState, PrivateState["memberPath"]],
    });

    console.debug("[contractClient] Contract instance created:", contractInstance);

    // Build providers using the connected wallet
    const serviceUris = await params.wallet.serviceUriConfig?.() || {
      nodeUri: "https://rpc.preprod.midnight.network",
      indexerUri: "https://indexer.preprod.midnight.network/api/v1/graphql",
      proverServerUri: "https://prover.preprod.midnight.network",
    };

    console.debug("[contractClient] Service URIs:", serviceUris);

    // The wallet extension provides the DApp connector; we pass providers to the SDK.
    // @ts-expect-error - Provider shape is complex and differs by SDK version; we pass the wallet directly.
    const deployedContractInstance = await findDeployedContract(
      {
        walletProvider: params.wallet,
        publicDataProvider: { ...serviceUris },
        zkConfigProvider: { ...serviceUris },
        proofProvider: { ...serviceUris },
      },
      {
        contractAddress: deployedContract.address as string,
        contract: contractInstance,
        privateStateKey: "enclave",
        initialPrivateState: {
          memberSecret: memberSecretBytes,
          memberPath: { leaf: memberSecretBytes, path: [] },
        },
      }
    );

    console.debug("[contractClient] Connected to deployed contract. Submitting enterRoom...");

    // Submit the real on-chain transaction
    const tx = await deployedContractInstance.callTx.enterRoom(BigInt(params.roomIndex));
    console.debug("[contractClient] Transaction submitted:", tx);

    const txHash: string =
      (tx as { public?: { txHash?: string }; txHash?: string })?.public?.txHash ??
      (tx as { txHash?: string })?.txHash ??
      "unknown";

    console.debug("[contractClient] txHash:", txHash);

    return {
      txHash,
      explorerUrl: `https://preprod.midnight.network/transaction/${txHash}`,
    };
  } catch (error) {
    console.error("[contractClient] Error during enterRoom:", error);
    throw new Error(`Failed to execute enterRoom on chain: ${error}`);
  }
}
